# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BMrecode <- function(A, a, b) {
    .Call('_nap_BMrecode', PACKAGE = 'nap', A, a, b)
}

BMsimulate <- function(A) {
    .Call('_nap_BMsimulate', PACKAGE = 'nap', A)
}

BMwrite012 <- function(A, outfile) {
    .Call('_nap_BMwrite012', PACKAGE = 'nap', A, outfile)
}

BMwritePED <- function(A, outfile) {
    .Call('_nap_BMwritePED', PACKAGE = 'nap', A, outfile)
}

BMsubset <- function(A, myrows, mycols) {
    .Call('_nap_BMsubset', PACKAGE = 'nap', A, myrows, mycols)
}

upperTmat <- function(mymat) {
    .Call('_nap_upperTmat', PACKAGE = 'nap', mymat)
}

Xmcenter <- function(X) {
    .Call('_nap_Xmcenter', PACKAGE = 'nap', X)
}

Xmvcenter <- function(X) {
    .Call('_nap_Xmvcenter', PACKAGE = 'nap', X)
}

LDrelative <- function(A, mycols, debug = FALSE) {
    .Call('_nap_LDrelative', PACKAGE = 'nap', A, mycols, debug)
}

rankC <- function(x) {
    .Call('_nap_rankC', PACKAGE = 'nap', x)
}

accuracies <- function(y, what) {
    .Call('_nap_accuracies', PACKAGE = 'nap', y, what)
}

My <- function(y, h) {
    .Call('_nap_My', PACKAGE = 'nap', y, h)
}

BMs <- function(A, y, mycols, myrows, debug = FALSE) {
    .Call('_nap_BMs', PACKAGE = 'nap', A, y, mycols, myrows, debug)
}

BMmgwa <- function(X0, yraw, debug = FALSE) {
    .Call('_nap_BMmgwa', PACKAGE = 'nap', X0, yraw, debug)
}

LLGaussMix <- function(y, w, v, p) {
    .Call('_nap_LLGaussMix', PACKAGE = 'nap', y, w, v, p)
}

LIKELIHOOD <- function(y, w, b, a, p, mu, epi, verbose = FALSE, printall = FALSE) {
    .Call('_nap_LIKELIHOOD', PACKAGE = 'nap', y, w, b, a, p, mu, epi, verbose, printall)
}

wC <- function(X, s, mode, epi = 1, verbose = FALSE) {
    .Call('_nap_wC', PACKAGE = 'nap', X, s, mode, epi, verbose)
}

wCBM <- function(A, s, mycols, myrows, mode, epi = 1, verbose = FALSE) {
    .Call('_nap_wCBM', PACKAGE = 'nap', A, s, mycols, myrows, mode, epi, verbose)
}

wCBMupdate <- function(wnew, A, mycols, myrows, indecito, s0, s1, mode) {
    invisible(.Call('_nap_wCBMupdate', PACKAGE = 'nap', wnew, A, mycols, myrows, indecito, s0, s1, mode))
}

wCBMupdateforR <- function(wnew, A, mycols, myrows, indecito, s0, s1, mode) {
    .Call('_nap_wCBMupdateforR', PACKAGE = 'nap', wnew, A, mycols, myrows, indecito, s0, s1, mode)
}

sampleWC <- function(w, a, b, p, rep) {
    .Call('_nap_sampleWC', PACKAGE = 'nap', w, a, b, p, rep)
}

ssaveC <- function(s, path) {
    .Call('_nap_ssaveC', PACKAGE = 'nap', s, path)
}

ssimC <- function(snps, svar) {
    .Call('_nap_ssimC', PACKAGE = 'nap', snps, svar)
}

rowSumsC <- function(x) {
    .Call('_nap_rowSumsC', PACKAGE = 'nap', x)
}

allelesimCvec <- function(mu = 0, nu = 0, m = 0, wAA = 1, wAa = 0.75, waa = 0.5, p0 = 0.5, psource = 0.1, Fi = 0, d = 0, N = 100L, tmax = 10L) {
    .Call('_nap_allelesimCvec', PACKAGE = 'nap', mu, nu, m, wAA, wAa, waa, p0, psource, Fi, d, N, tmax)
}

allelesimCmat <- function(mu = 0, nu = 0, m = 0, wAA = 1, wAa = 0.75, waa = 0.5, p0 = 0.5, psource = 0.1, Fi = 0, d = 0, N = 100L, tmax = 10L, rep = 10L) {
    .Call('_nap_allelesimCmat', PACKAGE = 'nap', mu, nu, m, wAA, wAa, waa, p0, psource, Fi, d, N, tmax, rep)
}

