---
title: "mcmccheck"
author: "Moi Exposito-Alonso"
date: '`r Sys.Date()`'
# output: html_document
output:
  #- \setlength{\parindent}{4em}
  #- \setlength{\parskip}{0em}
  
  pdf_document:
  header-inclusdes:
   - \usepackage{amsmath}
   - \usepackage{caption}
   - \usepackage{subcaption}
   - \usepackage{graphicx}
  #html_document: default
  #header-includes:
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
 setwd("~/GoogleDrive/RESEARCH/_nap/nap")

knitr::opts_chunk$set(echo = TRUE)
## Load packages
library(devtools)
library(dplyr)
library(ggplot2)
library(cowplot)
library(latex2exp)

library(coda)
library(Rcpp)
library(MCMCglmm)

library(moiR)
load_all('.')
# library(nap)

```



# Simple run without sampling variance
```{r , echo=T}


a=0.05
b=0.05
p=0
mu=1
svar=0.1
ss=0
epi=1
replicates=5
ss=0
n=500
m=3
maf=mafsim(m)
X <- XsimLD(n,m,maf,r2=0.8) # different from Xsim
cor(X)
s= ssim(m,svar)
Ey=wsim(X,s,mode=2)
y=sampleW(Ey,a,b,p,rep = replicates)
h=sort(rep.int(1:n,replicates))


x<-napMCMCwrap()

x$chain %>% tail
x$shat<- c(tail(x$chain,1))
LIKELIHOOD(y,h-1,wC(X,BMridge(X,My(y,h)),FITmode),b,a,p,mu,epi,verbose = F)
LIKELIHOOD(y,h-1,wC(X,x$shat,FITmode,x$par["epi",],x$par["mu",]),
                x$par["b",] ,x$par["a",],x$par["p",],x$par["mu",],x$par["epi",],verbose = F)
LIKELIHOOD(y,h-1,wC(X,s,FITmode),b,a,p,mu,epi,verbose = F)

```


```{r, fig.width=8,fig.height=8,fig.align='center'}



pnap<-scorplot(s,x$shat)
pnap
pgwa<-scorplot(s,BMridge(X,My(y,h),lambda = 10)) # conditional
pgwa
pfinal<-plot_grid(
          pnap$psel,
          pgwa$psel,
          labels=c("NAP","mGWA")
          )
# print(pfinal)


inap<-indplot(y,h,x$w)
igwa<-indplot(y,h,X %*% BMridge(X,My(y,h))+mu)
pfin2<-plot_grid(
          inap,
          igwa,
          labels=c("NAP","mGWA")
          )
# print(pfin2)
p<-plot_grid(pfinal,pfin2,ncol=1)
print(p)

```

