---
title: "Test fitness distributions and S from example simulations"
author: "Moi Exposito-Alonso"
date: '`r Sys.Date()`'
# output: html_document
output:
  #- \setlength{\parindent}{4em}
  #- \setlength{\parskip}{0em}
  
  pdf_document:
  header-inclusdes:
   - \usepackage{amsmath}
   - \usepackage{caption}
   - \usepackage{subcaption}
   - \usepackage{graphicx}
  #html_document: default
  #header-includes:
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
 
knitr::opts_chunk$set(echo = TRUE)
## Load packages
library(devtools)
library(dplyr)
library(ggplot2)
library(cowplot)
library(latex2exp)

library(coda)
library(Rcpp)

library(moiR)
load_all('.')
# library(nap)


```


```{r}
# Rcpp::sourceCpp('../MCMC.cpp')

svar=0.5
a=0.01
b=0.1
p=0

replicates=5
n=500
m=2
m=10

# Genome matrix
maf=mafsim(m)
qplot(x = maf) +labs(title="Simulated minimum allele frequency")
X <- Xsim(n,m,maf)

# Selectionc oefficient
s= ssim(m,svar)
qplot(s) +labs(title="Simulated selection coefficients")

# Fitness
Ey1=wsim(X,s,mode=1)
Ey2=wsim(X,s,mode=2)
Ey3=wsim(X,s,mode=3)
Ey=wsim(X,s,mode=1)
plot_grid(
          (qplot(Ey) + labs(title="Simulated true fitness values") ),
          (qplot(y=Ey, x=1+(X %*% s)) + labs(title="Check simulated additive with C++ vs R")),
          ncol=2
          )

# Fitness samples
y=sampleW(Ey,a,b,p,rep = replicates)
h=sort(rep.int(1:n,replicates))

qplot(y=y,x=Ey[h]) + labs(title="Simulated true fitness vs fitness with sampling variance")

```

Comparison additive vs multiplicative
```{r}
qplot(x=Ey1,y=Ey3) + labs(ylab=paste("Inverse multiplicative",epi), xlab="No epistasis")
qplot(x=Ey1,y=Ey2) + labs(ylab=paste("Multiplicative",epi), xlab="No epistasis")
qplot(x=Ey3,y=Ey2) + labs(ylab=paste("Multiplicative",epi), xlab="Inverse multiplicative")

```


Same parameters but epistasis. It is more pronounced with stronger selection
```{r}
# Rcpp::sourceCpp('../MCMC.cpp')



qplot(x=Ey,y=wsim(X,s,mode=1,epi=0.6)) + labs(ylab=paste("Global antagonistic epistasis",epi), xlab="No epistasis")
qplot(x=Ey,y=wsim(X,s,mode=1,epi=1.4)) + labs(ylab=paste("Global synergistic epistasis",epi), xlab="No epistasis")


```

