---
title: "mcmccheck"
author: "Moi Exposito-Alonso"
date: '`r Sys.Date()`'
# output: html_document
output:
  #- \setlength{\parindent}{4em}
  #- \setlength{\parskip}{0em}
  
  pdf_document:
  header-inclusdes:
   - \usepackage{amsmath}
   - \usepackage{caption}
   - \usepackage{subcaption}
   - \usepackage{graphicx}
  #html_document: default
  #header-includes:
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
 setwd("~/GoogleDrive/RESEARCH/_nap/nap")

knitr::opts_chunk$set(echo = TRUE)
## Load packages
library(devtools)
library(dplyr)
library(ggplot2)
library(cowplot)
library(latex2exp)

library(coda)
library(Rcpp)
library(MCMCglmm)

library(moiR)
load_all('.')
# library(nap)

```


# Simple run
```{r , echo=FALSE, fig.width=8,fig.height=12,fig.align='center'}

svar=0.05
ss=0
p=0
a=0.05
b=1
mu=1
epi=1
replicates=5
n=500
m=2
maf=mafsim(m)
X <- Xsim(n,m,maf)
s= ssim(m,svar)
Ey=wsim(X,s,mode=2)
y=sampleW(Ey,a,b,p,rep = replicates)
h=sort(rep.int(1:n,replicates))

# hist(y);  hist(Ey)

```

Test inintialization
```{r}
x<-test_napMCMC(y,h,X,m=1:m,n=1:n,rnorm(m,0,0.1),
           test=F,
           verbose=T,
           iterations=10,FITmode = 2,Smode = 2,
           PRImode = 2)

```

Test few steps
```{r}

x<-napMCMC(y,h,X,m=1:m,n=1:n,rnorm(m,0,0.1),
           test=F,
           verbose=T,
           iterations=100,FITmode = 2,Smode = 2,
           PRImode = 2)

plotNAP(x)

```

Test accuracy of minimal example
```{r}
x<-napMCMC(y,h,X,m=1:m,n=1:n,rnorm(m,0,0.1),
           test=F,
           verbose=F,
           iterations=10000,FITmode = 1,
           Smode = 1,
           PRImode = 1,
           bmin=b,bmax=b,
           amin=0,amax=a,
           pmin=p,pmax=p,
           mumin=1,mumax=1)
plot(x$posterior,ylab="Posterior")

ssummary(x$chain)

paramplot(x$parchain, truevalues =  c(b,a,p,mu,epi,svar,ss))
scorplot(c(b,a,p,mu,epi,svar,ss),posterior.mode(x$parchain))

cbind(
posterior.mode(x$parchain),
parnames()
)
scorplot(s,BMmgwa(X,My(y,h)))
scorplot(s,posterior.mode(x$chain))



# need to check that the proposals don't get outside the appropriate range.
```


# Example of accuracy plot
```{r}
scorplot(s,posterior.mode(x$chain))


```

# Example of parameter
