---
title: "mcmccheck"
author: "Moi Exposito-Alonso"
date: '`r Sys.Date()`'
# output: html_document
output:
  #- \setlength{\parindent}{4em}
  #- \setlength{\parskip}{0em}
  
  pdf_document:
  header-inclusdes:
   - \usepackage{amsmath}
   - \usepackage{caption}
   - \usepackage{subcaption}
   - \usepackage{graphicx}
  #html_document: default
  #header-includes:
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
## Load packages
library(devtools)
library(dplyr)
library(ggplot2)
library(cowplot)
library(latex2exp)

library(coda)
library(MCMCglmm)
library(Rcpp)

library(moiR)
load_all('.')
# library(nap)

```


# Mixing of chain
```{r , echo=FALSE, fig.width=8,fig.height=12,fig.align='center'}

svar=0.05
a=0.0
b=0.1
p=0
replicates=5
n=500
m=5
maf=mafsim(m)
X <- Xsim(n,m,maf)
s= ssim(m,svar)
Ey1=wsim(X,s,mode=1)
Ey2=wsim(X,s,mode=2)
Ey3=wsim(X,s,mode=3)
Ey=wsim(X,s,mode=1)
y=sampleW(Ey,a,b,p,rep = replicates)
h=sort(rep.int(1:n,replicates))
x<-napMCMC(y,h,X,m=1:m,n=1:n,rnorm(m,0,0.1),
            test=TRUE,
            iterations=10000,verbose = F, pro)
ssummary(x$chain)
shist(x$chain)

```
