---
title: "mcmccheck"
author: "Moi Exposito-Alonso"
date: '`r Sys.Date()`'
# output: html_document
output:
  #- \setlength{\parindent}{4em}
  #- \setlength{\parskip}{0em}
  
  pdf_document:
  header-inclusdes:
   - \usepackage{amsmath}
   - \usepackage{caption}
   - \usepackage{subcaption}
   - \usepackage{graphicx}
  #html_document: default
  #header-includes:
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
 setwd("~/GoogleDrive/RESEARCH/_nap/nap")

knitr::opts_chunk$set(echo = TRUE)
## Load packages
library(devtools)
library(dplyr)
library(ggplot2)
library(cowplot)
library(latex2exp)

library(coda)
library(Rcpp)

library(moiR)
load_all('.')
# library(nap)


```

# Test mcmc
```{r}
Rcpp::sourceCpp('MCMC.cpp')

svar=0.05
a=0.0
b=0.1
p=0
replicates=5
n=500
m=2
maf=mafsim(m)
hist(maf)
X <- Xsim(n,m,maf)
s= ssim(m,svar)
hist(s)
Ey1=wsim(X,s,mode=1)
Ey2=wsim(X,s,mode=2)
Ey3=wsim(X,s,mode=3)
Ey=wsim(X,s,mode=1)
hist(Ey)
plot(Ey, 1+(X %*% s))
hist(Ey); hist(1+(X %*% s))
y=sampleEys(Ey,a,b,p,rep = replicates)
hist(y)
h=sort(rep.int(1:n,replicates))
plot(y,Ey[h])

```



```{r}
 setwd("~/GoogleDrive/RESEARCH/_nap/nap")
Rcpp::sourceCpp('MCMC.cpp')

# Test no errors
x<-napMCMC(y,h,X,m=1:m,n=1:n,c(s),
            test=TRUE,
           iterations=100,
           verbose = TRUE)

# Test chain sampling uniformly
x<-napMCMC(y,h,X,m=1:m,n=1:n,c(s),
            test=TRUE,
           iterations=1e6,
           verbose = TRUE)
x$parchain %>%
  data.frame %>%
  dplyr::rename(b=X1,
                a=X2,
                p=X3,
                mu=X4,
                epi=X5,
                svar=X6,
                ss=X7) %>% as.mcmc() %>% plot

        
x<-napMCMC(y,h,X,m=1:m,n=1:n,c(s),
            test=FALSE,
           iterations=100,verbose = TRUE)
as.mcmc(x$chain) %>% summary

```



<!-- # Test chain -->
<!-- ```{r} -->
<!-- Rcpp::sourceCpp('tests.cpp') -->
<!-- test() -->

<!-- ``` -->
