# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BMsimulate <- function(A) {
    .Call('_nap_BMsimulate', PACKAGE = 'nap', A)
}

BMsubset <- function(A, myrows, mycols) {
    .Call('_nap_BMsubset', PACKAGE = 'nap', A, myrows, mycols)
}

upperTmat <- function(mymat) {
    .Call('_nap_upperTmat', PACKAGE = 'nap', mymat)
}

Xmcenter <- function(X) {
    .Call('_nap_Xmcenter', PACKAGE = 'nap', X)
}

Xmvcenter <- function(X) {
    .Call('_nap_Xmvcenter', PACKAGE = 'nap', X)
}

LDrelative <- function(A, m, debug = FALSE) {
    .Call('_nap_LDrelative', PACKAGE = 'nap', A, m, debug)
}

modeC <- function(ar) {
    .Call('_nap_modeC', PACKAGE = 'nap', ar)
}

modeCmat <- function(ar) {
    .Call('_nap_modeCmat', PACKAGE = 'nap', ar)
}

My <- function(y, h) {
    .Call('_nap_My', PACKAGE = 'nap', y, h)
}

BMmgwa <- function(X0, yraw, debug = FALSE) {
    .Call('_nap_BMmgwa', PACKAGE = 'nap', X0, yraw, debug)
}

BMcgwa <- function(X0, yraw) {
    .Call('_nap_BMcgwa', PACKAGE = 'nap', X0, yraw)
}

BMridge <- function(X0, yraw, lambda = 1) {
    .Call('_nap_BMridge', PACKAGE = 'nap', X0, yraw, lambda)
}

sample_num <- function(x, size, replace, prob = as.numeric( c())) {
    .Call('_nap_sample_num', PACKAGE = 'nap', x, size, replace, prob)
}

hsub <- function(h) {
    .Call('_nap_hsub', PACKAGE = 'nap', h)
}

runif_reflect <- function(minhere, maxhere, min, max) {
    .Call('_nap_runif_reflect', PACKAGE = 'nap', minhere, maxhere, min, max)
}

whichchanged <- function(s1, s2) {
    .Call('_nap_whichchanged', PACKAGE = 'nap', s1, s2)
}

logmixgaussian <- function(s, svar, ss) {
    .Call('_nap_logmixgaussian', PACKAGE = 'nap', s, svar, ss)
}

iterprior <- function(s, svar, ss) {
    .Call('_nap_iterprior', PACKAGE = 'nap', s, svar, ss)
}

PRIOR <- function(s, par1 = 0.1, par2 = 0.1, type = 2L) {
    .Call('_nap_PRIOR', PACKAGE = 'nap', s, par1, par2, type)
}

ePRIOR <- function(e, m = 1L, v = 0.2) {
    .Call('_nap_ePRIOR', PACKAGE = 'nap', e, m, v)
}

uPRIOR <- function(pri, s0, s1, par10 = 0.1, par11 = 0.1, par20 = 0.1, par21 = 0.1, type = 2L) {
    .Call('_nap_uPRIOR', PACKAGE = 'nap', pri, s0, s1, par10, par11, par20, par21, type)
}

LLGaussMix <- function(y, w, v, p) {
    .Call('_nap_LLGaussMix', PACKAGE = 'nap', y, w, v, p)
}

LIKELIHOOD <- function(y, hs, w, b, a, p, mu, epi, verbose = FALSE, LIKmode = 2L) {
    .Call('_nap_LIKELIHOOD', PACKAGE = 'nap', y, hs, w, b, a, p, mu, epi, verbose, LIKmode)
}

wC <- function(X, s, mode, epi = 1, mu = 1, verbose = FALSE) {
    .Call('_nap_wC', PACKAGE = 'nap', X, s, mode, epi, mu, verbose)
}

wCBM <- function(A, s, myrows, mycols, mode, epi = 1, mu = 1, verbose = FALSE) {
    .Call('_nap_wCBM', PACKAGE = 'nap', A, s, myrows, mycols, mode, epi, mu, verbose)
}

napMCMC <- function(y, h, A, m, n, s, b = 0.5, bmin = 0, bmax = 1, a = 0.1, amin = 0, amax = 1, p = 0.5, pmin = 0, pmax = 1, mu = 1, mumin = 0, mumax = 50, epi = 1, epimin = 1, epimax = 1, svar = 0.1, svarmin = 0.001, svarmax = 1, ss = 0.1, ssmin = 0, ssmax = 1, smin = -0.98039215686274505668, smax = 10, iterations = 1e4L, burnin = 0.1, Smode = 2L, LIKmode = 2L, PRImode = 1L, FITmode = 2L, verbose = FALSE, test = FALSE, updateratio = -9.0, bw = 0.001, file2sink = "output.log", sink2file = FALSE) {
    .Call('_nap_napMCMC', PACKAGE = 'nap', y, h, A, m, n, s, b, bmin, bmax, a, amin, amax, p, pmin, pmax, mu, mumin, mumax, epi, epimin, epimax, svar, svarmin, svarmax, ss, ssmin, ssmax, smin, smax, iterations, burnin, Smode, LIKmode, PRImode, FITmode, verbose, test, updateratio, bw, file2sink, sink2file)
}

test_napMCMC <- function(y, h, A, m, n, s, b = 0.5, bmin = 0, bmax = 1, a = 0.1, amin = 0, amax = 1, p = 0.5, pmin = 0, pmax = 1, mu = 1, mumin = 0, mumax = 50, epi = 1, epimin = 1, epimax = 1, svar = 0.1, svarmin = 0.001, svarmax = 1, ss = 0.1, ssmin = 0, ssmax = 1, smin = -0.98039215686274505668, smax = 10, iterations = 1e4L, burnin = 0.1, Smode = 2L, LIKmode = 2L, PRImode = 1L, FITmode = 2L, verbose = FALSE, test = FALSE, updateratio = -9.0, bw = 0.001, file2sink = "output.log", sink2file = FALSE) {
    .Call('_nap_test_napMCMC', PACKAGE = 'nap', y, h, A, m, n, s, b, bmin, bmax, a, amin, amax, p, pmin, pmax, mu, mumin, mumax, epi, epimin, epimax, svar, svarmin, svarmax, ss, ssmin, ssmax, smin, smax, iterations, burnin, Smode, LIKmode, PRImode, FITmode, verbose, test, updateratio, bw, file2sink, sink2file)
}

rowSumsC <- function(x) {
    .Call('_nap_rowSumsC', PACKAGE = 'nap', x)
}

allelesimCvec <- function(mu = 0, nu = 0, m = 0, wAA = 1, wAa = 0.75, waa = 0.5, p0 = 0.5, psource = 0.1, Fi = 0, d = 0, N = 100L, tmax = 10L) {
    .Call('_nap_allelesimCvec', PACKAGE = 'nap', mu, nu, m, wAA, wAa, waa, p0, psource, Fi, d, N, tmax)
}

allelesimCmat <- function(mu = 0, nu = 0, m = 0, wAA = 1, wAa = 0.75, waa = 0.5, p0 = 0.5, psource = 0.1, Fi = 0, d = 0, N = 100L, tmax = 10L, rep = 10L) {
    .Call('_nap_allelesimCmat', PACKAGE = 'nap', mu, nu, m, wAA, wAa, waa, p0, psource, Fi, d, N, tmax, rep)
}

